name: Update helm charts
on:
  workflow_call:
  workflow_dispatch:
jobs:
  update-sbomscanner-charts:
    name: Update SBOMscanner charts
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests:  read
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Updatecli in the runner
        uses: updatecli/updatecli-action@4fd2c16d992120bd5355264a03ad0cddec013e1b # v2.99.0

      # Helm and helm plugins installation required by the updatecli release action
      - name: Install helm
        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4.3.1
      - name: Install helm values schema json plugin
        # Disable plugin verification until helm v4 is supported
        run: helm plugin install https://github.com/losisin/helm-values-schema-json.git --verify=false

      - name: Update SBOMscanner charts
        env:
          UPDATECLI_GITHUB_APP_CLIENT_ID: ${{ secrets.APP_ID }}
          UPDATECLI_GITHUB_APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
          UPDATECLI_GITHUB_APP_INSTALLATION_ID: "${{ secrets.APP_INSTALLATION_ID }}"
        run: "updatecli compose apply --file updatecli/updatecli-compose.release.yaml"
